apiVersion: v1
kind: Secret
metadata:
  name: go-ws-gateway-proxy-secrets
stringData:
  # production values
  JWT_EXPECTED_ISSUER: "https://keycloak.example.com/realms/myrealm"
  JWT_EXPECTED_AUDIENCE: "rabbitmq"
  JWT_VALID_ALGORITHMS: "RS256"
  REDIS_URL: "redis://prod-redis.example.com:6379/0"
  POSTGRES_DSN: "postgresql://user:pass@prod-postgres.example.com:5432/dbname?sslmode=disable"
  UPSTREAM_WS_URL: "ws://rabbitmq-prod.example.com:15675/ws"
